#!/bin/sh

echo "1 - Landscape"
echo "2 - Portrait"
echo "3 - Auto"
read ori

if [ $ori = "3" ]
then 
    echo "Turning on automatic rotation"
    adb shell content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:1
elif [ $ori = "1" ]
then 
    echo "Turning off automatic rotation"
    adb shell content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:0
    echo "Rotating screen landscape"
    adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:1

elif [ $ori = "2" ]
then
    echo "Turning off automatic rotation"
    adb shell content insert --uri content://settings/system --bind name:s:accelerometer_rotation --bind value:i:0
    echo "Rotating screen landscape"
    adb shell content insert --uri content://settings/system --bind name:s:user_rotation --bind value:i:0
fi
